# networks:
  # monitoring:
    # driver: bridge

volumes:
  prometheus_data: {}

services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node
    network_mode: "host"
    # ports:
    # - '9100:9100'
    # networks:
    # - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - prometheus_data:/prometheus
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    - '--web.console.libraries=/etc/prometheus/console_libraries'
    - '--web.console.templates=/etc/prometheus/consoles'
    - '--web.enable-lifecycle'
    network_mode: "host"
    # ports:
    # - '9090:9090'
    # networks:
    # - monitoring

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    network_mode: "host"
    # ports:
    # - '3000:3000'
    # networks:
    # - monitoring
